# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mcserver.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 408)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtWidgets.QTextBrowser(self.tab)
        self.log.setDocumentTitle("")
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmdbox = QtWidgets.QLineEdit(self.tab)
        self.cmdbox.setInputMask("")
        self.cmdbox.setText("")
        self.cmdbox.setObjectName("cmdbox")
        self.horizontalLayout_2.addWidget(self.cmdbox)
        self.run = QtWidgets.QPushButton(self.tab)
        self.run.setObjectName("run")
        self.horizontalLayout_2.addWidget(self.run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_server = QtWidgets.QPushButton(self.tab)
        self.start_server.setObjectName("start_server")
        self.horizontalLayout.addWidget(self.start_server)
        self.stop_server = QtWidgets.QPushButton(self.tab)
        self.stop_server.setObjectName("stop_server")
        self.horizontalLayout.addWidget(self.stop_server)
        self.clear_log = QtWidgets.QPushButton(self.tab)
        self.clear_log.setObjectName("clear_log")
        self.horizontalLayout.addWidget(self.clear_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.max_ram = QtWidgets.QSpinBox(self.groupBox)
        self.max_ram.setMinimum(512)
        self.max_ram.setMaximum(9999999)
        self.max_ram.setObjectName("max_ram")
        self.gridLayout.addWidget(self.max_ram, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.java_help = QtWidgets.QPushButton(self.groupBox)
        self.java_help.setObjectName("java_help")
        self.gridLayout.addWidget(self.java_help, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.jar_list = QtWidgets.QComboBox(self.groupBox_3)
        self.jar_list.setObjectName("jar_list")
        self.verticalLayout.addWidget(self.jar_list)
        self.fresh_jar = QtWidgets.QPushButton(self.groupBox_3)
        self.fresh_jar.setObjectName("fresh_jar")
        self.verticalLayout.addWidget(self.fresh_jar)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eula = QtWidgets.QPushButton(self.groupBox_4)
        self.eula.setObjectName("eula")
        self.verticalLayout_4.addWidget(self.eula)
        self.open_pro = QtWidgets.QPushButton(self.groupBox_4)
        self.open_pro.setObjectName("open_pro")
        self.verticalLayout_4.addWidget(self.open_pro)
        self.help_pro = QtWidgets.QPushButton(self.groupBox_4)
        self.help_pro.setObjectName("help_pro")
        self.verticalLayout_4.addWidget(self.help_pro)
        self.del_pro = QtWidgets.QPushButton(self.groupBox_4)
        self.del_pro.setObjectName("del_pro")
        self.verticalLayout_4.addWidget(self.del_pro)
        self.save_map = QtWidgets.QPushButton(self.groupBox_4)
        self.save_map.setObjectName("save_map")
        self.verticalLayout_4.addWidget(self.save_map)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.debug = QtWidgets.QCheckBox(self.groupBox_2)
        self.debug.setObjectName("debug")
        self.verticalLayout_5.addWidget(self.debug)
        self.auto_update = QtWidgets.QCheckBox(self.groupBox_2)
        self.auto_update.setObjectName("auto_update")
        self.verticalLayout_5.addWidget(self.auto_update)
        self.reset_setting = QtWidgets.QPushButton(self.groupBox_2)
        self.reset_setting.setObjectName("reset_setting")
        self.verticalLayout_5.addWidget(self.reset_setting)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.save_setting = QtWidgets.QPushButton(self.tab_2)
        self.save_setting.setObjectName("save_setting")
        self.verticalLayout_7.addWidget(self.save_setting)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.dl_list = QtWidgets.QListWidget(self.tab_3)
        self.dl_list.setObjectName("dl_list")
        self.verticalLayout_8.addWidget(self.dl_list)
        self.fresh_dl_list = QtWidgets.QPushButton(self.tab_3)
        self.fresh_dl_list.setObjectName("fresh_dl_list")
        self.verticalLayout_8.addWidget(self.fresh_dl_list)
        self.download = QtWidgets.QPushButton(self.tab_3)
        self.download.setObjectName("download")
        self.verticalLayout_8.addWidget(self.download)
        self.downloading = QtWidgets.QLabel(self.tab_3)
        self.downloading.setObjectName("downloading")
        self.verticalLayout_8.addWidget(self.downloading)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancel_dl = QtWidgets.QPushButton(self.tab_3)
        self.cancel_dl.setObjectName("cancel_dl")
        self.horizontalLayout_6.addWidget(self.cancel_dl)
        self.pause_dl = QtWidgets.QPushButton(self.tab_3)
        self.pause_dl.setObjectName("pause_dl")
        self.horizontalLayout_6.addWidget(self.pause_dl)
        self.continue_dl = QtWidgets.QPushButton(self.tab_3)
        self.continue_dl.setObjectName("continue_dl")
        self.horizontalLayout_6.addWidget(self.continue_dl)
        self.dl_info = QtWidgets.QPushButton(self.tab_3)
        self.dl_info.setObjectName("dl_info")
        self.horizontalLayout_6.addWidget(self.dl_info)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.progress = QtWidgets.QProgressBar(self.tab_3)
        self.progress.setProperty("value", 100)
        self.progress.setObjectName("progress")
        self.verticalLayout_8.addWidget(self.progress)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.info = QtWidgets.QAction(MainWindow)
        self.info.setObjectName("info")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.update = QtWidgets.QAction(MainWindow)
        self.update.setObjectName("update")
        self.server_path = QtWidgets.QAction(MainWindow)
        self.server_path.setObjectName("server_path")
        self.menu.addAction(self.info)
        self.menu.addAction(self.server_path)
        self.menu_2.addAction(self.update)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "我的世界开服助手"))
        self.log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:13.5pt;\"><br /></p></body></html>"))
        self.cmdbox.setPlaceholderText(_translate("MainWindow", "在此输入命令"))
        self.run.setText(_translate("MainWindow", "执行命令"))
        self.start_server.setText(_translate("MainWindow", "启动服务器"))
        self.stop_server.setText(_translate("MainWindow", "停止服务器"))
        self.clear_log.setText(_translate("MainWindow", "清除日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "服务器"))
        self.groupBox.setTitle(_translate("MainWindow", "Java设置"))
        self.label_2.setText(_translate("MainWindow", "最大内存："))
        self.label.setText(_translate("MainWindow", "java路径："))
        self.label_3.setText(_translate("MainWindow", "（推荐设置为1024）"))
        self.label_5.setText(_translate("MainWindow", "暂不支持自定义java路径，请确保设置了正确的环境变量"))
        self.java_help.setText(_translate("MainWindow", "如何设置？"))
        self.groupBox_3.setTitle(_translate("MainWindow", "服务器核心"))
        self.label_4.setText(_translate("MainWindow", "将核心文件放入server文件夹然后点击刷新"))
        self.label_7.setText(_translate("MainWindow", "如果没有选择服务器核心文件将使用\\server\\server.jar"))
        self.fresh_jar.setText(_translate("MainWindow", "刷新"))
        self.groupBox_4.setTitle(_translate("MainWindow", "服务器配置"))
        self.eula.setText(_translate("MainWindow", "一键同意协议"))
        self.open_pro.setText(_translate("MainWindow", "打开服务器配置文件"))
        self.help_pro.setText(_translate("MainWindow", "查看服务器配置文件说明"))
        self.del_pro.setText(_translate("MainWindow", "重置服务器配置文件"))
        self.save_map.setText(_translate("MainWindow", "保存地图"))
        self.groupBox_2.setTitle(_translate("MainWindow", "软件设置"))
        self.debug.setText(_translate("MainWindow", "调试模式"))
        self.auto_update.setText(_translate("MainWindow", "启动时检查更新"))
        self.reset_setting.setText(_translate("MainWindow", "重置软件设置"))
        self.save_setting.setText(_translate("MainWindow", "保存此页设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "配置"))
        self.label_6.setText(_translate("MainWindow", "可用下载项："))
        self.fresh_dl_list.setText(_translate("MainWindow", "刷新列表"))
        self.download.setText(_translate("MainWindow", "下载选中项"))
        self.downloading.setText(_translate("MainWindow", "当前没有下载任务"))
        self.cancel_dl.setText(_translate("MainWindow", "取消当前下载任务"))
        self.pause_dl.setText(_translate("MainWindow", "暂停下载"))
        self.continue_dl.setText(_translate("MainWindow", "继续下载"))
        self.dl_info.setText(_translate("MainWindow", "查看下载任务信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "下载核心"))
        self.menu.setTitle(_translate("MainWindow", "服务器"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.action_2.setText(_translate("MainWindow", "自定义核心"))
        self.action_3.setText(_translate("MainWindow", "下载核心"))
        self.info.setText(_translate("MainWindow", "查看正在运行的服务器信息"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.update.setText(_translate("MainWindow", "检查更新"))
        self.server_path.setText(_translate("MainWindow", "打开服务器所在文件夹"))
